"""Add alert_zipcode to User

Revision ID: 982a43211c24
Revises: 5bf0a1b53629
Create Date: 2025-04-07 14:25:40.321546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982a43211c24'
down_revision = '5bf0a1b53629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_zipcode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alert_zipcode')

    # ### end Alembic commands ###
